FROM postgres:15-bookworm

ENV AGE_VERSION=1.5.0
ENV AGE_GIT_URL=https://github.com/apache/age.git
ENV PGVECTOR_VERSION=0.7.0

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    postgresql-server-dev-15 \
    libssl-dev \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --branch v${AGE_VERSION} ${AGE_GIT_URL} /tmp/age \
    && cd /tmp/age \
    && make install \
    && rm -rf /tmp/age

RUN wget -q https://github.com/pgvector/pgvector/archive/refs/tags/v${PGVECTOR_VERSION}.tar.gz \
    && tar -xzf v${PGVECTOR_VERSION}.tar.gz \
    && cd pgvector-${PGVECTOR_VERSION} \
    && make install \
    && cd .. \
    && rm -rf pgvector-${PGVECTOR_VERSION} v${PGVECTOR_VERSION}.tar.gz

RUN mkdir -p /docker-entrypoint-initdb.d

COPY database/init/ /docker-entrypoint-initdb.d/

RUN chown -R postgres:postgres /docker-entrypoint-initdb.d

COPY postgresql.conf /usr/local/share/postgresql/postgresql.conf.sample