// 题目-知识点关联图谱 (LLM标注)

MERGE (q:Question {id: 'annotated_数学_14355944', title: '一、选择题（共16分，每题2分）第1-8题均有四个选项，符合题意的选项只有一个．', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_14355944'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 【1.1.1】集合的含义与表示', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_14355944'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （1）集合的概念', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_14355944'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_数学_12790315', title: '2. 截至2021年12月31日，长江干流六座梯级水电站全年累计发电量达2628．83亿千瓦时，相当于减排二氧化碳约2.2亿吨．将262 883 000 000', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > 〖2.1〗指数函数', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_12790315'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > 【2.1.1】指数与指数幂的运算', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_12790315'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_数学_6907498', title: '4. 实数在数轴上的对应点的位置如图所示，下列结论中正确的是（    ）', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > N 表示自然数集，N 或N 表示正整数集，Z 表示整数集，Q表示有理数集，R表示实数集.', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_6907498'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > n an |a|  ．', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_6907498'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_数学_16666231', title: '一、选择题（本题共16分，每小题2分）第1-8题均有四个选项，符合题意的选项只有一个.', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > （1）根式的概念', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_16666231'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > ①如果xn a,aR,xR,n1，且nN ，那么x叫做a的n次方根．当n是奇数时，a的n次', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_16666231'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > ②式子n a叫做根式，这里n叫做根指数，a叫做被开方数．当n为奇数时，a为任意实数；当n为', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_16666231'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_数学_15465669', title: '1.4月24日是中国航天日，1970年的这一天，我国自行设计、制造的第一颗人造地球卫星“东方红一号”成功发射，标志着中国从此进入了太空时代，它的运行轨道，距地球', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > 〖2.1〗指数函数', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_15465669'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > 【2.1.1】指数与指数幂的运算', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_15465669'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_数学_1005609', title: '4.在数轴上，点A，B在原点O的两侧，分别表示数a，2，将点A向右平移1个单位长度，得到点C.若，则a的值为								（　　）', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （2）常用数集及其记法', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_1005609'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > N 表示自然数集，N 或N 表示正整数集，Z 表示整数集，Q表示有理数集，R表示实数集.', subject: '数学'})
WITH kp MATCH (q:Question {id: 'annotated_数学_1005609'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_物理_3487028', title: '一、单项选择', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 说明：凡矢量式中用“+”号都为合成符号，把矢量运算转化为代数运算的前提是', subject: '物理'})
WITH kp MATCH (q:Question {id: 'annotated_物理_3487028'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 在学习物理概念和规律时不能只记结论，还须弄清其中的道理，知道物理概念和规', subject: '物理'})
WITH kp MATCH (q:Question {id: 'annotated_物理_3487028'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 4牛顿第一定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'annotated_物理_3487028'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_物理_10476779', title: '1. 下列物品中，通常情况下属于导体的是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > d 15法拉第电磁感应定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'annotated_物理_10476779'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 10安培力：磁场对电流的作用力 16楞次定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'annotated_物理_10476779'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > F=BIL(BI) 方向：左手定则 17反射定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'annotated_物理_10476779'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_物理_10923510', title: '2. 如图所示的光现象中，由于光的反射形成的是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > F=BIL(BI) 方向：左手定则 17反射定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'annotated_物理_10923510'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 11洛仑兹力：磁场对运动电荷的作用力 18折射定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'annotated_物理_10923510'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_物理_8121488', title: '3. 下列用电器中，利用电流热效应工作的是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > d 15法拉第电磁感应定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'annotated_物理_8121488'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_物理_11251643', title: '4. 下列实例中，为了增大压强是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 6压力: F=PS=ghs 7动量守恒定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'annotated_物理_11251643'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_化学_14153709', title: '1. 空气的成分中，体积分数约占78%的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > （2）某些元素可以形成不同的单质（性质、结构不同）—同素异形体。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_14153709'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （3）各种元素在地壳中的质量分数各不相同，占前五位的依次是：O、Si、Al、Fe、Ca。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_14153709'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_化学_14862079', title: '2. 下列物质在O2中燃烧，火星四射，生成黑色固体的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_14862079'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_14862079'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （2）某些元素可以形成不同的单质（性质、结构不同）—同素异形体。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_14862079'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_化学_4799471', title: '3. 将CO2通入下列液体中，能产生白色沉淀的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '3．离子 > 离子是指带电荷的原子或原子团。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_4799471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > （2）存在离子的物质：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_4799471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > ②电解质溶液中：盐酸、NaOH溶液…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_4799471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_化学_4326237', title: '4. 下列物质能用作氮肥的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_4326237'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_4326237'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 阳离子：Li+、Na+、H+、NH+…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_4326237'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_化学_6495013', title: '5. 下列物质属于氧化物的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_6495013'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_6495013'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_化学_488628', title: '1. 下列自行车构件及配件所用的材料中，属于金属材料的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_488628'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_488628'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_488628'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_化学_235216', title: '2. 下列生活用品，利用金属导电性的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '3．离子 > ③金属晶体中：钠、铁、钾、铜…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_235216'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_化学_4217925', title: '3. 一些食物的pH范围如下，其中酸性最强的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_4217925'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_化学_5713151', title: '4. 垃圾分类人人有责。香蕉皮属于', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_5713151'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_5713151'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_化学_4777817', title: '5. 人体每日需要摄入适量的钙，这里的“钙”指的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_4777817'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_4777817'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （2）某些元素可以形成不同的单质（性质、结构不同）—同素异形体。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'annotated_化学_4777817'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_语文_13920681', title: '一、基础·运用（共13分）', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 这个单元的鉴赏重点是情感与意象。', subject: '语文'})
WITH kp MATCH (q:Question {id: 'annotated_语文_13920681'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 如何体会诗中的情感呢？尤其是如何把握比较含蓄甚至隐晦的诗歌如《雨巷》等表达', subject: '语文'})
WITH kp MATCH (q:Question {id: 'annotated_语文_13920681'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 意象是诗歌理论中一个非常重要的概念。“意”即欣赏者的心意、情志，“象”即形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'annotated_语文_13920681'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_语文_7429472', title: '3. 你检查了文段中成语使用的情况。下列成语使用不恰当的一项是（   ）', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第四单元................................................................... 70 > 第 1', subject: '语文'})
WITH kp MATCH (q:Question {id: 'annotated_语文_7429472'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 一、单元教材及重点说明：', subject: '语文'})
WITH kp MATCH (q:Question {id: 'annotated_语文_7429472'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 本单元有诗歌可以共用一个“情”字来概括：《沁园春·长沙》中的革命豪情，《雨', subject: '语文'})
WITH kp MATCH (q:Question {id: 'annotated_语文_7429472'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_语文_12179664', title: '4. 小组成员讨论应如何理解文段中的“冲击”。你根据语境判断，下列正确的一项是（   ）', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 这个单元的鉴赏重点是情感与意象。', subject: '语文'})
WITH kp MATCH (q:Question {id: 'annotated_语文_12179664'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 如何体会诗中的情感呢？尤其是如何把握比较含蓄甚至隐晦的诗歌如《雨巷》等表达', subject: '语文'})
WITH kp MATCH (q:Question {id: 'annotated_语文_12179664'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 意象是诗歌理论中一个非常重要的概念。“意”即欣赏者的心意、情志，“象”即形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'annotated_语文_12179664'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_英语_15831933', title: '一、单项填空', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '核心单词 > vt.&vi. 增加；加；加起来；补充说； 又说', subject: '英语'})
WITH kp MATCH (q:Question {id: 'annotated_英语_15831933'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > addto增添；增加；增进', subject: '英语'})
WITH kp MATCH (q:Question {id: 'annotated_英语_15831933'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > add...to...把……增添到……', subject: '英语'})
WITH kp MATCH (q:Question {id: 'annotated_英语_15831933'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_英语_4551621', title: '3. ——       do you usually go to school, Mary?', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > （2）单项填空', subject: '英语'})
WITH kp MATCH (q:Question {id: 'annotated_英语_4551621'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_英语_4345401', title: '4. Many people like pandas       they are cute.', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > （2）单项填空', subject: '英语'})
WITH kp MATCH (q:Question {id: 'annotated_英语_4345401'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_英语_15831933', title: '一、单项填空', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '核心单词 > vt.&vi. 增加；加；加起来；补充说； 又说', subject: '英语'})
WITH kp MATCH (q:Question {id: 'annotated_英语_15831933'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > addto增添；增加；增进', subject: '英语'})
WITH kp MATCH (q:Question {id: 'annotated_英语_15831933'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > add...to...把……增添到……', subject: '英语'})
WITH kp MATCH (q:Question {id: 'annotated_英语_15831933'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_英语_9633025', title: '3. — Excuse me,     .is this T-shirt?', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > （2）单项填空', subject: '英语'})
WITH kp MATCH (q:Question {id: 'annotated_英语_9633025'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'annotated_英语_2508959', title: '4. — Lily, _____ you finish the letter in ten minutes?', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > （2）单项填空', subject: '英语'})
WITH kp MATCH (q:Question {id: 'annotated_英语_2508959'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
