// LLM知识点标注关联图谱 - 合并版
// 包含: 北京中考(240题) + 高考抽样(80题)

// === 北京中考题目-知识点关联 ===
MERGE (q:Question {id: 'zk_化学_16562550', title: '1. 空气的成分中，体积分数约占78%的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_16562550'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （3）各种元素在地壳中的质量分数各不相同，占前五位的依次是：O、Si、Al、Fe、Ca。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_16562550'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_13185846', title: '2. 下列物质在O2中燃烧，火星四射，生成黑色固体的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_13185846'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （2）某些元素可以形成不同的单质（性质、结构不同）—同素异形体。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_13185846'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_3732478', title: '3. 将CO2通入下列液体中，能产生白色沉淀的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '3．离子 > 离子是指带电荷的原子或原子团。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_3732478'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > （2）存在离子的物质：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_3732478'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > ①离子化合物中：NaCl、CaCl、NaSO…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_3732478'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_13736349', title: '4. 下列物质能用作氮肥的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '1．分子 > （1）分子同原子、离子一样是构成物质的基本微粒．', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_13736349'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 阳离子：Li+、Na+、H+、NH+…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_13736349'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_13736349'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_16626384', title: '5. 下列物质属于氧化物的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_16626384'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_16626384'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_4857803', title: '6. 下列仪器不能加热的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_4857803'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_9273065', title: '7. 下列物质含有氢分子的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '1．分子 > 分子是能够独立存在并保持物质化学性质的一种微粒。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_9273065'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_9273065'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1．分子 > 双原子分子如：O、H、HCl、NO…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_9273065'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_14595110', title: '8. 下列物质能除铁锈的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_14595110'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_14595110'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_9822656', title: '9. 电解水实验如图，下列说法不正确的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_9822656'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1．分子 > （1）分子同原子、离子一样是构成物质的基本微粒．', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_9822656'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_9822656'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_13442931', title: '10. 下列元素中，人体摄入过低会引起贫血的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_13442931'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （3）各种元素在地壳中的质量分数各不相同，占前五位的依次是：O、Si、Al、Fe、Ca。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_13442931'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_14754451', title: '1. 下列自行车构件及配件所用的材料中，属于金属材料的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_14754451'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_14754451'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > ③金属晶体中：钠、铁、钾、铜…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_14754451'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_2470730', title: '2. 下列生活用品，利用金属导电性的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2470730'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2470730'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > ③金属晶体中：钠、铁、钾、铜…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2470730'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_391626', title: '3. 一些食物的pH范围如下，其中酸性最强的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_391626'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 阳离子：Li+、Na+、H+、NH+…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_391626'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_4428536', title: '4. 垃圾分类人人有责。香蕉皮属于', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_4428536'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_4428536'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_9594959', title: '5. 人体每日需要摄入适量的钙，这里的“钙”指的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_9594959'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_9594959'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （2）某些元素可以形成不同的单质（性质、结构不同）—同素异形体。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_9594959'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_2320606', title: '6. 化肥对提高农作物的产量具有重要作用。下列物质能用作钾肥的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2320606'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 离子是指带电荷的原子或原子团。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2320606'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2320606'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_3948306', title: '7. 化石燃料是不可再生的能源，下列不属于化石燃料的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_3948306'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_3948306'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_5540497', title: '8. 赤铁矿(主要成分是Fe2O3)用于工业炼铁。Fe2O3中铁元素的化合价为', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_5540497'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 离子是指带电荷的原子或原子团。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_5540497'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_5540497'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_2396378', title: '9. 下列灭火措施不正确的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2396378'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2396378'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_2961144', title: '10. 空气中氧气的体积分数约为（　　）', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > （3）各种元素在地壳中的质量分数各不相同，占前五位的依次是：O、Si、Al、Fe、Ca。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2961144'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_14754451', title: '1. 下列自行车构件及配件所用的材料中，属于金属材料的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_14754451'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_14754451'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > ③金属晶体中：钠、铁、钾、铜…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_14754451'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_2470730', title: '2. 下列生活用品，利用金属导电性的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '3．离子 > ③金属晶体中：钠、铁、钾、铜…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2470730'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2470730'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_391626', title: '3. 一些食物的pH范围如下，其中酸性最强的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_391626'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_4428536', title: '4. 垃圾分类人人有责。香蕉皮属于', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_4428536'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_9594959', title: '5. 人体每日需要摄入适量的钙，这里的“钙”指的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_9594959'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_9594959'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_2320606', title: '6. 化肥对提高农作物的产量具有重要作用。下列物质能用作钾肥的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '3．离子 > 离子是指带电荷的原子或原子团。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2320606'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 阳离子：Li+、Na+、H+、NH+…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2320606'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 阴离子：Cl–、O2–、OH–、SO2–…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2320606'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_3948306', title: '7. 化石燃料是不可再生的能源，下列不属于化石燃料的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_3948306'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_3948306'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_5540497', title: '8. 赤铁矿(主要成分是Fe2O3)用于工业炼铁。Fe2O3中铁元素的化合价为', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_5540497'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_5540497'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_2396378', title: '9. 下列灭火措施不正确的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2396378'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_2961144', title: '10. 空气中氧气的体积分数约为（　　）', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > （3）各种元素在地壳中的质量分数各不相同，占前五位的依次是：O、Si、Al、Fe、Ca。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2961144'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_6923102', title: '11. 下列符号中，表示两个氧原子的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_6923102'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '2．原子 > 原子是化学变化中的最小微粒。确切地说，在化学反应中原子核不变，只有核外电子发生变化。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_6923102'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 离子是指带电荷的原子或原子团。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_6923102'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_14187820', title: '12. 下列氧气的性质中，属于化学性质的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_14187820'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_14187820'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_15914755', title: '13. 下列不属于氧气用途的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_15914755'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_15914755'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_1165863', title: '14. 下列操作不正确的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_1165863'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_6229520', title: '15. 下列物质放入水中能形成溶液是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_6229520'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_6229520'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_11271681', title: '16. 下列物质露置于空气中一段时间，质量会减少的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_11271681'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_10269442', title: '17. 下列关于水的说法中，不正确的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_10269442'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_10269442'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1．分子 > 多原子分子如：HO、P、CH O…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_10269442'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_5997698', title: '18. 下列说法不正确的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_5997698'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_10485030', title: '19. 下列方法能区分氮气和二氧化碳两瓶气体的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_10485030'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_10485030'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_3017500', title: '20. 火箭推进剂涉及的下列元素中，属于金属元素的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_3017500'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （3）各种元素在地壳中的质量分数各不相同，占前五位的依次是：O、Si、Al、Fe、Ca。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_3017500'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_13475766', title: '1. 下列变化属于化学变化的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_13475766'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_13475766'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_4096765', title: '2. 如表列出了某食品的营养成分，其中含量最高的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_4096765'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （1）元素与物质、分子、原子的区别与联系：物质是由元素组成的（宏观看）；物质是由分子、原子', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_4096765'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （3）各种元素在地壳中的质量分数各不相同，占前五位的依次是：O、Si、Al、Fe、Ca。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_4096765'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_5286531', title: '3. 下列物质属于纯净物的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_5286531'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_5286531'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_652625', title: '4. 垃圾分类对保护土壤具有重要意义、下列属于厨余垃圾的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_652625'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_2007587', title: '6. 为防治大气污染，下列做法不可行的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2007587'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_2007587'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_13358097', title: '8. 下列标志表示“禁止烟火”的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_13358097'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_5445485', title: '9. 下列物质混合后产生白色沉淀的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '3．离子 > 离子是指带电荷的原子或原子团。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_5445485'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > （2）存在离子的物质：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_5445485'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > ①离子化合物中：NaCl、CaCl、NaSO…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_5445485'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_化学_7100088', title: '10. 嫦娥六号探测器钻杆主体采用铝基碳化硅材料。铝、碳、硅是三种不同的元素，决定元素种类的是', subject: '化学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_7100088'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '5．同位素 > 是指同一元素不同核素之间互称同位素，即具有相同质子数，不同中子数的同一类原子互称同位素。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_7100088'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '2．原子 > （2）原子是由原子核（中子、质子）和核外电子构成的。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'zk_化学_7100088'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_13497620', title: '一、选择题（共16分，每题2分）第1-8题均有四个选项，符合题意的选项只有一个．', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_13497620'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 【1.1.1】集合的含义与表示', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_13497620'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （1）集合的概念', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_13497620'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_8238569', title: '2. 截至2021年12月31日，长江干流六座梯级水电站全年累计发电量达2628．83亿千瓦时，相当于减排二氧化碳约2.2亿吨．将262 883 000 000', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > 〖2.1〗指数函数', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_8238569'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > 【2.1.1】指数与指数幂的运算', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_8238569'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_4811779', title: '4. 实数在数轴上的对应点的位置如图所示，下列结论中正确的是（    ）', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > N 表示自然数集，N 或N 表示正整数集，Z 表示整数集，Q表示有理数集，R表示实数集.', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_4811779'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_10000103', title: '6. 若关于的一元二次方程有两个相等的实数根，则实数的值为（    ）', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 一、方程的根与函数的零点', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_10000103'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 方程 f(x)0有实数根函数 y  f(x)的图象与x轴有交点函数 y  f(x)有零点．', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_10000103'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > ○1 （代数法）求方程 f(x)0的实数根；', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_10000103'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_2586390', title: '8. 下面的三个问题中都有两个变量：', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 1、函数零点的概念：对于函数 y  f(x)(xD) ，把使 f(x)0 成立的实数 x 叫做函数', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_2586390'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 2、函数零点的意义：函数 y  f(x)的零点就是方程 f(x)0实数根，亦即函数 y  f(x)的图象', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_2586390'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > ○2 （几何法）对于不能用求根公式的方程，可以将它与函数y  f(x)的图象联系起来，并利用', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_2586390'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_4888766', title: '二、填空题（共16分，每题2分）', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 一、方程的根与函数的零点', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_4888766'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 1、函数零点的概念：对于函数 y  f(x)(xD) ，把使 f(x)0 成立的实数 x 叫做函数', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_4888766'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > y  f(x)(xD)的零点。', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_4888766'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_2297392', title: '9. 若在实数范围内有意义，则实数x的取值范围是___________．', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > （1）根式的概念', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_2297392'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > ②式子n a叫做根式，这里n叫做根指数，a叫做被开方数．当n为奇数时，a为任意实数；当n为', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_2297392'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_12657052', title: '11. 方程解为___________．', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 一、方程的根与函数的零点', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_12657052'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > ○1 （代数法）求方程 f(x)0的实数根；', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_12657052'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_6974519', title: '12. 在平面直角坐标系中，若点在反比例函数的图象上，则______（填“>”“=”或“<”）', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > 〖2.1〗指数函数', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_6974519'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > 【2.1.1】指数与指数幂的运算', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_6974519'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_8846742', title: '16. 甲工厂将生产的I号、II号两种产品共打包成5个不同的包裹，编号分别为A，B，C，D，E，每个包裹的重量及包裹中I号、II号产品的重量如下：', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_8846742'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （1）集合的概念', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_8846742'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 集合中的元素具有确定性、互异性和无序性.', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_8846742'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_11777659', title: '一、选择题（本题共16分，每小题2分）第1-8题均有四个选项，符合题意的选项只有一个.', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （2）常用数集及其记法', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_11777659'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > N 表示自然数集，N 或N 表示正整数集，Z 表示整数集，Q表示有理数集，R表示实数集.', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_11777659'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_2715988', title: '1.4月24日是中国航天日，1970年的这一天，我国自行设计、制造的第一颗人造地球卫星“东方红一号”成功发射，标志着中国从此进入了太空时代，它的运行轨道，距地球', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > 〖2.1〗指数函数', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_2715988'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > 【2.1.1】指数与指数幂的运算', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_2715988'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_13038294', title: '4.在数轴上，点A，B在原点O的两侧，分别表示数a，2，将点A向右平移1个单位长度，得到点C.若，则a的值为								（　　）', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > N 表示自然数集，N 或N 表示正整数集，Z 表示整数集，Q表示有理数集，R表示实数集.', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_13038294'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_2670163', title: '6.如果，那么代数式的值为				（　　）', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > 【2.1.1】指数与指数幂的运算', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_2670163'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > n an |a|  ．', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_2670163'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_数学_8731275', title: '二、填空题（本题共16分，每小题2分）', subject: '数学', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 一、方程的根与函数的零点', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_8731275'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 1、函数零点的概念：对于函数 y  f(x)(xD) ，把使 f(x)0 成立的实数 x 叫做函数', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_8731275'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > y  f(x)(xD)的零点。', subject: '数学'})
WITH kp MATCH (q:Question {id: 'zk_数学_8731275'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_13554813', title: '1. 下列物品中，通常情况下属于导体的是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > d 15法拉第电磁感应定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_13554813'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 10安培力：磁场对电流的作用力 16楞次定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_13554813'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > F=BIL(BI) 方向：左手定则 17反射定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_13554813'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_4496627', title: '2. 如图所示的光现象中，由于光的反射形成的是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > F=BIL(BI) 方向：左手定则 17反射定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_4496627'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 11洛仑兹力：磁场对运动电荷的作用力 18折射定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_4496627'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_12811534', title: '3. 下列用电器中，利用电流热效应工作的是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > 10安培力：磁场对电流的作用力 16楞次定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_12811534'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_1115994', title: '4. 下列实例中，为了增大压强是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 6压力: F=PS=ghs 7动量守恒定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_1115994'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 4牛顿第一定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_1115994'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_1292098', title: '5. 下列做法中符合安全用电要求的是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > d 15法拉第电磁感应定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_1292098'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 10安培力：磁场对电流的作用力 16楞次定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_1292098'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > F=BIL(BI) 方向：左手定则 17反射定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_1292098'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_9832218', title: '6. 下列实例中，为了减小摩擦的是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 3滑动摩擦力：F =N A 3滑动摩擦定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_9832218'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 4静摩擦力： Of', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_9832218'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_2822471', title: '7. 下列实例中，属于做功改变物体内能的是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > 大而减小,随距离的减小而增大,但斥力变化得快 ． 。 ②动能定理B做功跟动能改变的关系', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_2822471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_12958562', title: '10. 小军做凸透镜成像规律的实验时，将焦距为10cm的凸透镜固定在光具座上50cm刻度线处，光屏和点燃的蜡烛分别位于凸透镜两侧，蜡烛放置在35cm刻度线处，如', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > 11洛仑兹力：磁场对运动电荷的作用力 18折射定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_12958562'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_13770944', title: '12. 小海设计了一种测定油箱内油量的模拟装置，如图所示，其中电源两端电压保持不变，R0是定值电阻，R是滑动变阻器的电阻片，滑动变阻器的滑片P跟滑杆的一端连接，', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 5浮力： F =gV 6牛顿第三定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_13770944'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > d 15法拉第电磁感应定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_13770944'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_6602600', title: '14. 中国科技馆有一个由小车和螺旋桨组成的装置，如图所示．小车在磁体间的相互作用下悬浮于水平平直轨道上．按下控制开关，小车左端的螺旋桨开始转动，小车由静止开始', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 1重力： G=mg (g随高度、纬度、不同星球上不同) 1万有引力定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_6602600'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 4牛顿第一定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_6602600'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 8机械能守恒定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_6602600'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_8897892', title: '15. 如图所示，盛有水杯子静止在水平桌面上．杯子重1N，高9cm，底面积30cm2；杯内水重2N，水深6cm，水的密度为1.0×103kg/m3，g取10N/', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 6压力: F=PS=ghs 7动量守恒定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_8897892'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 1重力： G=mg (g随高度、纬度、不同星球上不同) 1万有引力定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_8897892'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_12693746', title: '17. 下列说法中正确的是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > d 15法拉第电磁感应定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_12693746'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 10安培力：磁场对电流的作用力 16楞次定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_12693746'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > F=BIL(BI) 方向：左手定则 17反射定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_12693746'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_13992761', title: '18. 下列说法中正确的是（  ）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > 12分子力：分子间的引力和斥力同时存在,都随距离的增 ①动量定理B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_13992761'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 大而减小,随距离的减小而增大,但斥力变化得快 ． 。 ②动能定理B做功跟动能改变的关系', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_13992761'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_933920', title: '一、单项选择题（下列每题均有四个选项，其中只有一个选项符合题意。共24分，每题2分）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > 1静止或作匀速直线运动（平衡态问题）；', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_933920'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: 'Ⅱ运动分类：（各种运动产生的力学和运动学条件及运动规律）是高中物理的重点、难点 > ①匀速直线运动 F', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_933920'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: 'Ⅱ运动分类：（各种运动产生的力学和运动学条件及运动规律）是高中物理的重点、难点 > =0 a=0 V0 ≠0', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_933920'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_物理_13858031', title: '1. 下列物品中，通常情况下属于导体的是（　　）', subject: '物理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '电 > d 15法拉第电磁感应定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'zk_物理_13858031'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_13520426', title: '4. — Lily, _____ you finish the letter in ten minutes?', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > （2）单项填空', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_13520426'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_846123', title: '5. This cap is nice,      it doesn’t look good on me.', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > （2）单项填空', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_846123'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_9848413', title: '7. Sam      with his friends every weekend.', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > （2）单项填空', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_9848413'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_10155159', title: '11. My advice on how to save paper      by my class last Monday.', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > （2）单项填空', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_10155159'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_6701550', title: '12. — Did you notice      in her office?', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > （2）单项填空', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_6701550'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_3922894', title: '13. A. bored	B. afraid	C. excited	D. hopeful', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > 用upset的适当形式填空（原创）', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_3922894'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '高手过招 > ①Thefood mystomach.', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_3922894'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '高手过招 > ①upset ②upset ③upsetting ④upset', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_3922894'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_6116527', title: '14. A. compare	B. remember	C. manage	D. repeat', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > 3.ignore', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_6116527'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '高手过招 > vt. 不理睬；忽视', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_6116527'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '高手过招 > Isaidhellotoher,butsheignoredmecompletely.', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_6116527'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_11585949', title: '15. A. fully	B. quickly	C. freshly	D. physically', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '易混辨析 > ignore/neglect/overlook', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_11585949'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '易混辨析 > ignore 通常指有意不顾，或不理会显而易见的事物。', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_11585949'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '易混辨析 > neglect 侧重指有意的忽略或忽视，也可指粗心与疏忽。', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_11585949'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_141955', title: '16. A. feared	B. faced	C. mentioned	D. pictured', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '核心单词 > Unit1 Friendship', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_141955'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '高手过招 > 3.ignore', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_141955'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '高手过招 > vt. 不理睬；忽视', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_141955'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_12535525', title: '17. A. insist	B. return	C. wait	D. win', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > 3.ignore', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_12535525'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '高手过招 > vt. 不理睬；忽视', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_12535525'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '高手过招 > Isaidhellotoher,butsheignoredmecompletely.', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_12535525'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_12855169', title: '18. A. suggestion	B. prediction	C. direction	D. introduction', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '核心单词 > Unit1 Friendship', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_12855169'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > PageNo.11', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_12855169'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_英语_13520426', title: '4. — Lily, _____ you finish the letter in ten minutes?', subject: '英语', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > （2）单项填空', subject: '英语'})
WITH kp MATCH (q:Question {id: 'zk_英语_13520426'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_语文_8619334', title: '7. 文段中的第①～④句是小组成员对各个文化生活场所的描述。你从修辞的角度判断，下列使用修辞手法的一项是（   ）', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 这个单元的鉴赏重点是情感与意象。', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_8619334'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 意象是诗歌理论中一个非常重要的概念。“意”即欣赏者的心意、情志，“象”即形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_8619334'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 的思想情感呢？可主要从了解诗歌的创作背景、诗人的思想生平和诗中运用的表现手法三', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_8619334'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_语文_2183298', title: '二、古诗文阅读（共17分）', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 这个单元的鉴赏重点是情感与意象。', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_2183298'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 如何体会诗中的情感呢？尤其是如何把握比较含蓄甚至隐晦的诗歌如《雨巷》等表达', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_2183298'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 意象是诗歌理论中一个非常重要的概念。“意”即欣赏者的心意、情志，“象”即形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_2183298'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_语文_15814626', title: '9. 根据你的理解，在下面横线上填写恰当的内容。', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 这个单元的鉴赏重点是情感与意象。', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_15814626'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 意象是诗歌理论中一个非常重要的概念。“意”即欣赏者的心意、情志，“象”即形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_15814626'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 象、物象，意象即审美主体眼中的形象或心中的物象，是主体与客体的统一，有形与无形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_15814626'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_语文_12280018', title: '10. 诗人写被秋风卷走的屋茅用了“三重”，写自己期待的“广厦”用了“千万间”。其中的“三”和“千万”都不是确定的数量，而是言其多。说说这样的用词蕴含作者怎样的', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 这个单元的鉴赏重点是情感与意象。', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_12280018'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 的思想情感呢？可主要从了解诗歌的创作背景、诗人的思想生平和诗中运用的表现手法三', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_12280018'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 意象是诗歌理论中一个非常重要的概念。“意”即欣赏者的心意、情志，“象”即形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_12280018'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_语文_9870142', title: '10. ①“三重”茅被风卷走，侧面烘托出深秋时节，狂风呼号，气候恶劣，凸显了诗人生活的艰辛，也暗示着社会动荡，民生疾苦，表达了诗人对现实的深切感受。②“千万间广', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 这个单元的鉴赏重点是情感与意象。', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_9870142'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 的思想情感呢？可主要从了解诗歌的创作背景、诗人的思想生平和诗中运用的表现手法三', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_9870142'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 意象是诗歌理论中一个非常重要的概念。“意”即欣赏者的心意、情志，“象”即形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_9870142'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_语文_16050928', title: '三、名著阅读（5分）', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 这个单元的鉴赏重点是情感与意象。', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_16050928'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 如何体会诗中的情感呢？尤其是如何把握比较含蓄甚至隐晦的诗歌如《雨巷》等表达', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_16050928'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 意象是诗歌理论中一个非常重要的概念。“意”即欣赏者的心意、情志，“象”即形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_16050928'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_语文_13418724', title: '一、基础·运用（共13分）', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 这个单元的鉴赏重点是情感与意象。', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_13418724'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 意象是诗歌理论中一个非常重要的概念。“意”即欣赏者的心意、情志，“象”即形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_13418724'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 象、物象，意象即审美主体眼中的形象或心中的物象，是主体与客体的统一，有形与无形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_13418724'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_语文_9603622', title: '3. 你检查文段中使用的成语后发现，下列成语使用不恰当的一项是（   ）', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 意象是诗歌理论中一个非常重要的概念。“意”即欣赏者的心意、情志，“象”即形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_9603622'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 象、物象，意象即审美主体眼中的形象或心中的物象，是主体与客体的统一，有形与无形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_9603622'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第1课 沁园春·长沙 > 一、文学常识：', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_9603622'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_语文_1182324', title: '5. 文段中的画线句存在问题，你做出修改。', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 意象是诗歌理论中一个非常重要的概念。“意”即欣赏者的心意、情志，“象”即形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_1182324'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 象、物象，意象即审美主体眼中的形象或心中的物象，是主体与客体的统一，有形与无形', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_1182324'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 这个单元的鉴赏重点是情感与意象。', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_1182324'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_语文_968572', title: '6. 根据小组意见，在横线处补写一个节奏匀称的句子。下列选项恰当的一项是（   ）', subject: '语文', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 这个单元的鉴赏重点是情感与意象。', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_968572'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 如何体会诗中的情感呢？尤其是如何把握比较含蓄甚至隐晦的诗歌如《雨巷》等表达', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_968572'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一单元——诗歌 > 个方面入手。要多读，所谓“操千曲而后晓声，观千剑而后识器”（刘勰）说的就是这个', subject: '语文'})
WITH kp MATCH (q:Question {id: 'zk_语文_968572'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_政治_16259738', title: '1. 中国共产党第二十次全国代表大会，是在全党全国各族人民迈上全面建设社会主义现代化国家新征程、向第二个百年奋斗目标进军的关键时刻召开的一次十分重要的大会。大会', subject: '政治', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '（5）中国共产党的性质：中国共产党是我国社会主义现代化建设事业的领导核心，这是由我国的社会主 > 义国家性质和党的性质（中国共产党是中国工人阶级的先锋队，同时也', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_16259738'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '（5）中国共产党的性质：中国共产党是我国社会主义现代化建设事业的领导核心，这是由我国的社会主 > 的社会环境、调动各方面的各级因素）；中国共产党对国家和社会生活', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_16259738'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_政治_13377547', title: '3. 小强和小军是好朋友，两个人都是校乒乓球队主力。', subject: '政治', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '（4）我国的公民与国家：正确对待公民的权利和义务（坚持公民法律面前一律平等的原则；坚持公民权 > 利和义务相统一的原则—认真行使权利自觉履行义务；坚持个人利益与', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_13377547'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_政治_3884933', title: '4. 打开手机软件，系统自动读屏，并一一给出语音提示。看新闻，靠文字识别技术“读”出资讯；想购物，图片转语音“描绘”商品详情……借助信息无障碍技术，视障者可以在', subject: '政治', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '（4）我国的公民与国家：正确对待公民的权利和义务（坚持公民法律面前一律平等的原则；坚持公民权 > 利和义务相统一的原则—认真行使权利自觉履行义务；坚持个人利益与', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_3884933'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_政治_1548744', title: '5. 社会生活离不开规则。有同学说，规则像道路上的斑马线，像悬崖边上的护栏，像过山车上的安全带。这一说法启示我们（    ）', subject: '政治', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '（4）我国的公民与国家：正确对待公民的权利和义务（坚持公民法律面前一律平等的原则；坚持公民权 > 利和义务相统一的原则—认真行使权利自觉履行义务；坚持个人利益与', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_1548744'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_政治_13219006', title: '6. 1936年4月，一支红军部队经过杜正云居住的村子时，将一位病重的小战士托付给他的外公、爷爷和大伯等人照料。他们毫不犹豫地答应了，并表示一定尽力照顾好这位小', subject: '政治', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '（4）我国的公民与国家：正确对待公民的权利和义务（坚持公民法律面前一律平等的原则；坚持公民权 > 利和义务相统一的原则—认真行使权利自觉履行义务；坚持个人利益与', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_13219006'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_政治_2738807', title: '10. 北京市着力探索社区“微治理”，形成超大城市治理“首都样板”。某社区健全以党建引领为核心的协商议事机制，完善居委会、业委会、业主、物业服务企业和社会单位共', subject: '政治', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '（1）我国的国体和政体：我国的国体是人民民主专政的社会主义国家；我国的国家职能，是由我国的国 > 家性质决定的并反映我国的国家性质，我国的国家职能有对内职能（依', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_2738807'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '（5）中国共产党的性质：中国共产党是我国社会主义现代化建设事业的领导核心，这是由我国的社会主 > 义国家性质和党的性质（中国共产党是中国工人阶级的先锋队，同时也', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_2738807'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '（2）我国的人民代表大会制度：中华人民共和国的一切权力属于人民，人民行使国家权力的机关是全国 > 人民代表大会和地方各级人民代表大会，我国的政权组织形式是人民代', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_2738807'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_政治_14893404', title: '11. 能用于手机的超薄柔性可折叠玻璃，厚度仅为A4纸的四分之一；普通手机可直连北斗卫星发信息，解决“不在服务区”难题；180千瓦高效率氢燃料电池发动机系统性能', subject: '政治', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '（1）我国的国体和政体：我国的国体是人民民主专政的社会主义国家；我国的国家职能，是由我国的国 > 活动；组织领导社会主义经济建设—宏观调控、社会管理、公共服务；', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_14893404'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '（1）我国的国体和政体：我国的国体是人民民主专政的社会主义国家；我国的国家职能，是由我国的国 > 的稳定；组织领导社会主义精神文明建设—教科文卫事业；搞好社会公', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_14893404'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '（5）中国共产党的性质：中国共产党是我国社会主义现代化建设事业的领导核心，这是由我国的社会主 > 义国家性质和党的性质（中国共产党是中国工人阶级的先锋队，同时也', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_14893404'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_政治_13032118', title: '12. 建设教育强国是全面建成社会主义现代化强国的战略先导。上图是2022年我国教育事业发展取得的成绩单，由此可推断出（    ）', subject: '政治', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '（1）我国的国体和政体：我国的国体是人民民主专政的社会主义国家；我国的国家职能，是由我国的国 > 的稳定；组织领导社会主义精神文明建设—教科文卫事业；搞好社会公', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_13032118'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_政治_13523475', title: '14. 带领学生研学旅行的指导师，帮助你“收拾心情”的整理收纳师，负责民宿管理的民宿管家，数字经济发展中催生的数据分析师、人工智能训练师、农业数字化技术员……这', subject: '政治', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '(1)社会主义初级阶段的经济制度：公有制是社会主义经济制度的基础 巩固和发展公有制经济，鼓励、支 > 持和引导非公有制经济发展以按劳分配为主体，多种分配方式并存', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_13523475'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '(2)劳动者的权利和义务：劳动者的基本权利和义务 扩大就业，创造更多的就业岗位劳动合同制度 我国 > 的社会保障制度', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_13523475'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_政治_3977057', title: '15. 中国与中亚五国是友好邻邦。', subject: '政治', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '(1)当代世界市场：世界市场的形成和发展 世界性贸易与金融组织 经济全球化 外汇与汇率 我国社会主 > 义市场经济必须面向世界', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_3977057'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '（1）我国的国体和政体：我国的国体是人民民主专政的社会主义国家；我国的国家职能，是由我国的国 > 捍卫国家主权和领土完整；发展国际交流与合作，创造有利于我国发展', subject: '政治'})
WITH kp MATCH (q:Question {id: 'zk_政治_3977057'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_地理_2345788', title: '2. 图中自然景观差异的形成，主要是由于（   ）', subject: '地理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '三：地球公转的地理意义 > （1）昼夜长短和正午太阳高度的变化', subject: '地理'})
WITH kp MATCH (q:Question {id: 'zk_地理_2345788'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '三：地球公转的地理意义 > ①昼夜长短的变化', subject: '地理'})
WITH kp MATCH (q:Question {id: 'zk_地理_2345788'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '三：地球公转的地理意义 > ②正午太阳高度的变化', subject: '地理'})
WITH kp MATCH (q:Question {id: 'zk_地理_2345788'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_地理_4305583', title: '6. 四地中（   ）', subject: '地理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '三：地球公转的地理意义 > （1）昼夜长短和正午太阳高度的变化', subject: '地理'})
WITH kp MATCH (q:Question {id: 'zk_地理_4305583'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '三：地球公转的地理意义 > ①昼夜长短的变化', subject: '地理'})
WITH kp MATCH (q:Question {id: 'zk_地理_4305583'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '三：地球公转的地理意义 > 北半球：夏半年，昼长夜短，越向北昼越长 ①太阳直射点在那个半球，', subject: '地理'})
WITH kp MATCH (q:Question {id: 'zk_地理_4305583'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_地理_16027894', title: '15. 柑橘种植区（   ）', subject: '地理', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '三：地球公转的地理意义 > （1）昼夜长短和正午太阳高度的变化', subject: '地理'})
WITH kp MATCH (q:Question {id: 'zk_地理_16027894'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '三：地球公转的地理意义 > ①昼夜长短的变化', subject: '地理'})
WITH kp MATCH (q:Question {id: 'zk_地理_16027894'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '三：地球公转的地理意义 > ②正午太阳高度的变化', subject: '地理'})
WITH kp MATCH (q:Question {id: 'zk_地理_16027894'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_3273928', title: '1. 除病毒外，生物体结构和功能的基本单位是（ ）', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元 生命的物质基础和结构基础 > （细胞中的化合物、细胞的结构和功能、细胞增殖、分化、癌变和衰老、生物膜系统和细胞工程）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_3273928'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_2323285', title: '2. 下列由一个细胞构成，能独立完成生命活动的生物是（　　）', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元 生命的物质基础和结构基础 > （细胞中的化合物、细胞的结构和功能、细胞增殖、分化、癌变和衰老、生物膜系统和细胞工程）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_2323285'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_13505944', title: '3. 在显微镜下观察洋葱鳞片叶内表皮临时装片，视野如下图。下列相关叙述错误的是（　　）', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元 生命的物质基础和结构基础 > （细胞中的化合物、细胞的结构和功能、细胞增殖、分化、癌变和衰老、生物膜系统和细胞工程）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_13505944'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_15788679', title: '4. 正常情况下，人体细胞在形态、结构和生理功能上发生差异，形成多种类型细胞的过程称为（　　）', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元 生命的物质基础和结构基础 > （细胞中的化合物、细胞的结构和功能、细胞增殖、分化、癌变和衰老、生物膜系统和细胞工程）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_15788679'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_5610293', title: '2．生态系统中，生产者（植物）能够通过光合作用制造有机物，并将光能储存在有机物中，为自身和其他生物提供了食物和能量，因此，能量流动的起点是从植物固定太阳能开始的', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元 生命的物质基础和结构基础 > （细胞中的化合物、细胞的结构和功能、细胞增殖、分化、癌变和衰老、生物膜系统和细胞工程）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_5610293'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_13011289', title: '7. 用黄豆种子发豆芽，下列做法不合理的是（　　）', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > 水 ④提供反应场所', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_13011289'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ⑤参与化学反应', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_13011289'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ⑥维持生物大分子功能', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_13011289'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_16774415', title: '8. 平衡膳食能最大程度地满足人体的营养需要，保证健康。下列做法不符合平衡膳食的是（　　）', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > 化合物 分 类 元素组成 主要生理功能', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_16774415'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ①构成化合物（Fe、Mg）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_16774415'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ③参与化学反应', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_16774415'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_259254', title: '9. 同学们按下图所示进行实验，一段时间后向两支试管中分别滴加碘液，观察颜色变化。下列叙述错误的是（　　）', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > 化合物 分 类 元素组成 主要生理功能', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_259254'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ②维持细胞形态', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_259254'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > 水 ④提供反应场所', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_259254'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ⑤参与化学反应', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_259254'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ⑥维持生物大分子功能', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_259254'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ⑦调节渗透压', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_259254'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ①构成化合物（Fe、Mg）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_259254'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ②组成细胞（如骨细胞）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_259254'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ③参与化学反应', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_259254'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ④维持细胞和内环境的渗透压）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_259254'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_9559351', title: '10. 血液成分中，富含血红蛋白，具有运输氧功能的是（    ）', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > 化合物 分 类 元素组成 主要生理功能', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_9559351'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1.4 细胞中的化合物一览表 > ①构成化合物（Fe、Mg）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_9559351'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_13056036', title: '11. 一位B型血的外伤患者需要大量输血，应为他输入（　　）', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元 生命的物质基础和结构基础 > （细胞中的化合物、细胞的结构和功能、细胞增殖、分化、癌变和衰老、生物膜系统和细胞工程）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_13056036'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_4916837', title: '12. 人体产生的代谢废物主要以尿液的形式排出体外。健康人的尿液中一般不含（　　）', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元 生命的物质基础和结构基础 > （细胞中的化合物、细胞的结构和功能、细胞增殖、分化、癌变和衰老、生物膜系统和细胞工程）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_4916837'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'zk_生物_3299203', title: '13. 下列关于人体肺泡的叙述错误的是（　　）', subject: '生物', source: 'zhongkao'})
MERGE (kp:KnowledgePoint {name: '第一单元 生命的物质基础和结构基础 > （细胞中的化合物、细胞的结构和功能、细胞增殖、分化、癌变和衰老、生物膜系统和细胞工程）', subject: '生物'})
WITH kp MATCH (q:Question {id: 'zk_生物_3299203'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

// === 高考题目-知识点关联 ===
MERGE (q:Question {id: 'gk_化学_14800685', title: '一、选择题（本题共 7小题，每小题 6分，共 42分）', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_14800685'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_14800685'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_14800685'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_3385071', title: '1．（6分）下列化合物中同分异构体数目最少的是（ ）', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '5．同位素 > 是指同一元素不同核素之间互称同位素，即具有相同质子数，不同中子数的同一类原子互称同位素。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_3385071'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '1．分子 > （2）按组成分子的原子个数可分为：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_3385071'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （2）某些元素可以形成不同的单质（性质、结构不同）—同素异形体。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_3385071'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_9289315', title: '2．（6分）化学与社会、生活密切相关，对下列现象或事实的解释正确的是（ ）', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_9289315'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （2）某些元素可以形成不同的单质（性质、结构不同）—同素异形体。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_9289315'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_9289315'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_5351811', title: '3．（6分）已知分解1mol H O 放出热量98kJ，在含少量I﹣的溶液中，H O 分解', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '3．离子 > 离子是指带电荷的原子或原子团。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_5351811'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 阴离子：Cl–、O2–、OH–、SO2–…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_5351811'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > ②电解质溶液中：盐酸、NaOH溶液…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_5351811'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_13457089', title: '1．（6分）化学与生活密切相关，下列有关说法错误的是（ ）', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_13457089'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （2）某些元素可以形成不同的单质（性质、结构不同）—同素异形体。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_13457089'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （3）各种元素在地壳中的质量分数各不相同，占前五位的依次是：O、Si、Al、Fe、Ca。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_13457089'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_8968412', title: '2．（6分）设N 为阿伏加德罗常数值．下列有关叙述正确的是（ ）', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_8968412'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_8968412'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '2．原子 > （2）原子是由原子核（中子、质子）和核外电子构成的。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_8968412'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_3478196', title: '3．（6分）下列关于有机化合物的说法正确的是（ ）', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_3478196'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （2）某些元素可以形成不同的单质（性质、结构不同）—同素异形体。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_3478196'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_3478196'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_7464083', title: '4．（6分）下列实验操作能达到实验目的是（ ）', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_7464083'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_7464083'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_9488785', title: '一、选择题：本题共 14小题，每小题 3分，共 42分。在每小题给出的四个选项中，只有一', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_9488785'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_9488785'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_9488785'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_4995185', title: '1. 近年来，我国新能源产业得到了蓬勃发展，下列说法错误的是', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '4．元素 > （2）某些元素可以形成不同的单质（性质、结构不同）—同素异形体。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_4995185'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_4995185'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_4995185'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_13168131', title: '2. 下列化学用语表述错误的是', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_13168131'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_13168131'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '5．同位素 > 是指同一元素不同核素之间互称同位素，即具有相同质子数，不同中子数的同一类原子互称同位素。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_13168131'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_13034659', title: '一、选择题：本题共 10小题，每小题 3分，共 30 分。在每小题给出的四个选项中，只有一', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_13034659'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_13034659'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '5．同位素 > 是指同一元素不同核素之间互称同位素，即具有相同质子数，不同中子数的同一类原子互称同位素。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_13034659'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_7087890', title: '1．（5 分）下列各组离子，在溶液中能大量共存、加入 NaOH 溶液后加热既有', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '3．离子 > 离子是指带电荷的原子或原子团。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_7087890'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > ②电解质溶液中：盐酸、NaOH溶液…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_7087890'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_11521320', title: '2．（5分）将15mL 2mol•L﹣1 Na CO 溶液逐滴加入到40mL 0.5mol•L﹣1 MCl 盐', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '3．离子 > 离子是指带电荷的原子或原子团。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_11521320'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 阳离子：Li+、Na+、H+、NH+…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_11521320'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 阴离子：Cl–、O2–、OH–、SO2–…', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_11521320'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_15080789', title: '3．（5分）下列表示溶液中发生反应的化学方程式错误的是（ ）', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > （一）掌握基本概念', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_15080789'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > 离子是指带电荷的原子或原子团。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_15080789'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '3．离子 > （2）存在离子的物质：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_15080789'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_化学_9854526', title: '7．（5分）有关下图所示化合物的说法不正确的是 （ ）', subject: '化学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一部分 化学基本概念和基本理论 > 一．物质的组成、性质和分类：', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_9854526'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > 元素是具有相同核电荷数（即质子数）的同—类原子的总称。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_9854526'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '4．元素 > （2）某些元素可以形成不同的单质（性质、结构不同）—同素异形体。', subject: '化学'})
WITH kp MATCH (q:Question {id: 'gk_化学_9854526'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_4035063', title: '一、选择题：本题共8小题，每小题5分，共40分，在每小题给出的四个选项中，只有一', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_4035063'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 1、函数零点的概念：对于函数 y  f(x)(xD) ，把使 f(x)0 成立的实数 x 叫做函数', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_4035063'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > y  f(x)(xD)的零点。', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_4035063'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_5860471', title: '1. 2，8，14，16，20 平均数为（ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_5860471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 集合中的元素具有确定性、互异性和无序性.', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_5860471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_530333', title: '3. A{4,0,1,2,8} B {x|x3  x}，AB （ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （3）集合与元素间的关系', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 一、方程的根与函数的零点', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_8867421', title: '4. 2解集是（ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_8867421'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （4）集合的表示法', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_8867421'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_4035063', title: '一、选择题：本题共8小题，每小题5分，共40分，在每小题给出的四个选项中，只有一', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_4035063'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 一、方程的根与函数的零点', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_4035063'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 1、函数零点的概念：对于函数 y  f(x)(xD) ，把使 f(x)0 成立的实数 x 叫做函数', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_4035063'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_5860471', title: '1. 2，8，14，16，20 平均数为（ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_5860471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 集合中的元素具有确定性、互异性和无序性.', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_5860471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （2）常用数集及其记法', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_5860471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_530333', title: '3. A{4,0,1,2,8} B {x|x3  x}，AB （ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （1）集合的概念', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （3）集合与元素间的关系', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_8867421', title: '4. 2解集是（ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_8867421'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > （1）根式的概念', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_8867421'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > ①如果xn a,aR,xR,n1，且nN ，那么x叫做a的n次方根．当n是奇数时，a的n次', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_8867421'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_4035063', title: '一、选择题：本题共8小题，每小题5分，共40分，在每小题给出的四个选项中，只有一', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_4035063'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 一、方程的根与函数的零点', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_4035063'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_5860471', title: '1. 2，8，14，16，20 平均数为（ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_5860471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 【1.1.1】集合的含义与表示', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_5860471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （1）集合的概念', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_5860471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_530333', title: '3. A{4,0,1,2,8} B {x|x3  x}，AB （ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （3）集合与元素间的关系', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 一、方程的根与函数的零点', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_8867421', title: '4. 2解集是（ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_8867421'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 【1.1.1】集合的含义与表示', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_8867421'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （1）集合的概念', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_8867421'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_4035063', title: '一、选择题：本题共8小题，每小题5分，共40分，在每小题给出的四个选项中，只有一', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_4035063'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 一、方程的根与函数的零点', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_4035063'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 1、函数零点的概念：对于函数 y  f(x)(xD) ，把使 f(x)0 成立的实数 x 叫做函数', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_4035063'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_5860471', title: '1. 2，8，14，16，20 平均数为（ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_5860471'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_530333', title: '3. A{4,0,1,2,8} B {x|x3  x}，AB （ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > （4）集合的表示法', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 一、方程的根与函数的零点', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_530333'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_数学_8867421', title: '4. 2解集是（ ）', subject: '数学', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '第一章 集合与函数概念 > 〖1.1〗集合', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_8867421'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第二章 基本初等函数(Ⅰ) > n an |a|  ．', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_8867421'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '第三章 函数的应用 > 方程 f(x)0有实数根函数 y  f(x)的图象与x轴有交点函数 y  f(x)有零点．', subject: '数学'})
WITH kp MATCH (q:Question {id: 'gk_数学_8867421'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_6156907', title: '一、选择题（本题共 8小题，每小题 6分，在每小题给出的四个选项中，第 1-5', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 说明：凡矢量式中用“+”号都为合成符号，把矢量运算转化为代数运算的前提是', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_6156907'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 在学习物理概念和规律时不能只记结论，还须弄清其中的道理，知道物理概念和规', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_6156907'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: 'Ⅱ运动分类：（各种运动产生的力学和运动学条件及运动规律）是高中物理的重点、难点 > ．．．．．．．．．．．．．', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_6156907'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_4337992', title: '1．（6分）两相邻匀强磁场区域的磁感应强度大小不同、方向平行。一速度方向', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '电 > 11洛仑兹力：磁场对运动电荷的作用力 18折射定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_4337992'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > F=BIL(BI) 方向：左手定则 17反射定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_4337992'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 10安培力：磁场对电流的作用力 16楞次定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_4337992'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_5638639', title: '3．（6分）一理想变压器的原，副线圈的匝数比为3：', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '电 > d 15法拉第电磁感应定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_5638639'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 10安培力：磁场对电流的作用力 16楞次定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_5638639'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_616393', title: '4．（6 分）如图，一半径为 R，粗糙程度处处相同的半圆形轨道竖直固定放置，', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 3滑动摩擦力：F =N A 3滑动摩擦定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_616393'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > fm(由运动趋势和平衡方程去判断) 5牛顿第二定律B 力学', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_616393'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 大而减小,随距离的减小而增大,但斥力变化得快 ． 。 ②动能定理B做功跟动能改变的关系', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_616393'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_7232994', title: '用橡皮擦干净后，再选涂其他答案标号。回答非选择题时，将答案写在答题卡上。写在本试', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 说明：凡矢量式中用“+”号都为合成符号，把矢量运算转化为代数运算的前提是', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_7232994'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 在学习物理概念和规律时不能只记结论，还须弄清其中的道理，知道物理概念和规', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_7232994'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: 'Ⅱ运动分类：（各种运动产生的力学和运动学条件及运动规律）是高中物理的重点、难点 > ．．．．．．．．．．．．．', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_7232994'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_530982', title: '3.考试结束后，将本试卷和答题卡一并交回。', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 说明：凡矢量式中用“+”号都为合成符号，把矢量运算转化为代数运算的前提是', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_530982'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 在学习物理概念和规律时不能只记结论，还须弄清其中的道理，知道物理概念和规', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_530982'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_13152476', title: '一、选择题：本题共 6小题，每小题 4分，共 24 分。在每小题给出的四个选项中，只有一项', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 说明：凡矢量式中用“+”号都为合成符号，把矢量运算转化为代数运算的前提是', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_13152476'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 在学习物理概念和规律时不能只记结论，还须弄清其中的道理，知道物理概念和规', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_13152476'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: 'Ⅱ运动分类：（各种运动产生的力学和运动学条件及运动规律）是高中物理的重点、难点 > ．．．．．．．．．．．．．', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_13152476'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_12444302', title: '1．答卷前，考生务必将自己的姓名、准考证号填写在本试卷和答题卡上．', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 说明：凡矢量式中用“+”号都为合成符号，把矢量运算转化为代数运算的前提是', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_12444302'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 在学习物理概念和规律时不能只记结论，还须弄清其中的道理，知道物理概念和规', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_12444302'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_9164416', title: '2．回答选择题时，选出每小题答案后，用铅笔把答题卡上对应题目的答案标号涂黑．如需', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 说明：凡矢量式中用“+”号都为合成符号，把矢量运算转化为代数运算的前提是', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_9164416'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 在学习物理概念和规律时不能只记结论，还须弄清其中的道理，知道物理概念和规', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_9164416'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_8794028', title: '3．考试结束后，将本试卷和答题卡一并交回．', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 说明：凡矢量式中用“+”号都为合成符号，把矢量运算转化为代数运算的前提是', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_8794028'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 在学习物理概念和规律时不能只记结论，还须弄清其中的道理，知道物理概念和规', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_8794028'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_998872', title: '一、选择题：本题共 6小题，每小题 4分，共 24分．在每小题给出的四个选项中，只有一', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 说明：凡矢量式中用“+”号都为合成符号，把矢量运算转化为代数运算的前提是', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_998872'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 在学习物理概念和规律时不能只记结论，还须弄清其中的道理，知道物理概念和规', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_998872'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 1静止或作匀速直线运动（平衡态问题）；', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_998872'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_9436196', title: '一、选择题：本大题共 8 小题，每小题 6 分．在每小题给出的四个选项中，第', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 说明：凡矢量式中用“+”号都为合成符号，把矢量运算转化为代数运算的前提是', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_9436196'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 在学习物理概念和规律时不能只记结论，还须弄清其中的道理，知道物理概念和规', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_9436196'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: 'Ⅱ运动分类：（各种运动产生的力学和运动学条件及运动规律）是高中物理的重点、难点 > ．．．．．．．．．．．．．', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_9436196'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_16599765', title: '1．（6分）将质量为1.00kg的模型火箭点火升空，50g燃烧的燃气以大小为600m/s', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力的种类:（13个性质力） 有18条定律、2条定理 > 6压力: F=PS=ghs 7动量守恒定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_16599765'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 12分子力：分子间的引力和斥力同时存在,都随距离的增 ①动量定理B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_16599765'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_5298438', title: '二、选择题：本大题共 8 小题，每小题 6 分．在每小题给出的四个选项中，第', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 说明：凡矢量式中用“+”号都为合成符号，把矢量运算转化为代数运算的前提是', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_5298438'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '力学问题中的“过程”、“状态”的分析和建立及应用物理模型在物理学习中是至关重要的。 > 在学习物理概念和规律时不能只记结论，还须弄清其中的道理，知道物理概念和规', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_5298438'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: 'Ⅱ运动分类：（各种运动产生的力学和运动学条件及运动规律）是高中物理的重点、难点 > 高考中常出现多种运动形式的组合 追及(直线和圆)和碰撞、平抛、竖直上抛、匀速', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_5298438'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_物理_10112884', title: '2．（6分）现代质谱仪可用来分析比质子重很多的离子，其示意图如图所示，其', subject: '物理', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '电 > 11洛仑兹力：磁场对运动电荷的作用力 18折射定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_10112884'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > F=BIL(BI) 方向：左手定则 17反射定律', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_10112884'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '电 > 10安培力：磁场对电流的作用力 16楞次定律B', subject: '物理'})
WITH kp MATCH (q:Question {id: 'gk_物理_10112884'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_英语_3178891', title: '2. 选择题必须使用 2B 铅笔填涂; 非选择题必须使用 0.5 毫米黑色字迹的签字笔书写, 字体', subject: '英语', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '核心单词 > Unit1 Friendship', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_3178891'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > PageNo.11', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_3178891'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_英语_16665632', title: '5. What is Alex doing?', subject: '英语', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '核心单词 > vt.&vi. 增加；加；加起来；补充说； 又说', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_16665632'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > Headdedsomewoodtoincreasethefire.', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_16665632'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > 他添了一些木柴，使火更旺些。', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_16665632'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_英语_7069868', title: '6. Where is Ben?', subject: '英语', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '核心单词 > Unit1 Friendship', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_7069868'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > PageNo.11', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_7069868'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_英语_13031101', title: '7. What will the children in the afternoon?', subject: '英语', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '核心单词 > Unit1 Friendship', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_13031101'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > PageNo.11', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_13031101'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_英语_3216911', title: '1. What will Lucy do at 11:30 tomorrow?', subject: '英语', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '核心单词 > Unit1 Friendship', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_3216911'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_英语_3892809', title: '7. What will the man do?', subject: '英语', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '高手过招 > （2）单项填空', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_3892809'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_英语_714686', title: '2.回答选择题时, 选出每小题答案后, 用铅笔把答题卡上对应题目的答案标号涂黑。如需改动,', subject: '英语', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '核心单词 > Unit1 Friendship', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_714686'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > PageNo.11', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_714686'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)

MERGE (q:Question {id: 'gk_英语_10774198', title: '用橡皮擦干净后, 再选涂其他答案标号。回答非选择题时, 将答案写在答题卡上, 写在本试卷', subject: '英语', source: 'gaokao'})
MERGE (kp:KnowledgePoint {name: '核心单词 > Unit1 Friendship', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_10774198'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
MERGE (kp:KnowledgePoint {name: '核心单词 > PageNo.11', subject: '英语'})
WITH kp MATCH (q:Question {id: 'gk_英语_10774198'}) MERGE (q)-[:TESTS_KNOWLEDGE]->(kp)
